#!/bin/bash

# Install committy as a git hook
# Usage: ./install-git-hook.sh [--global]

HOOK_TYPE="prepare-commit-msg"
GLOBAL_FLAG=""

if [ "$1" = "--global" ]; then
    GLOBAL_FLAG="--global"
    echo "Installing global git hook template..."
    
    # Create global hooks directory
    HOOKS_DIR="$HOME/.git-templates/hooks"
    mkdir -p "$HOOKS_DIR"
    
    # Set global template directory
    git config --global init.templateDir "$HOME/.git-templates"
else
    echo "Installing local git hook..."
    
    # Check if we're in a git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        echo "Error: Not in a git repository. Run from repo root or use --global flag."
        exit 1
    fi
    
    HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
fi

HOOK_FILE="$HOOKS_DIR/$HOOK_TYPE"

# Create the hook script
cat > "$HOOK_FILE" << 'EOF'
#!/bin/bash

# Committy AI-powered commit message hook
# Generated by install-git-hook.sh

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"
SHA1="$3"

# Only run for regular commits (not merges, rebases, squashes, etc.)
if [ -n "$COMMIT_SOURCE" ]; then
    exit 0
fi

# Check if committy is available
if ! command -v committy >/dev/null 2>&1; then
    echo "# Committy not found in PATH - skipping AI commit message generation" >> "$COMMIT_MSG_FILE"
    exit 0
fi

# Check if we have staged changes
if git diff --cached --quiet; then
    exit 0
fi

# Check for API key
if [ -z "$CLAUDE_API_KEY" ]; then
    echo "# CLAUDE_API_KEY not set - skipping AI commit message generation" >> "$COMMIT_MSG_FILE"
    exit 0
fi

# Generate AI commit message suggestions
echo "# Generating AI commit message suggestions..." >> "$COMMIT_MSG_FILE"
echo "#" >> "$COMMIT_MSG_FILE"

# Get suggestions and format them as comments
if SUGGESTIONS=$(committy --no-commit 2>/dev/null); then
    echo "# AI-generated suggestions (uncomment and edit as needed):" >> "$COMMIT_MSG_FILE"
    echo "#" >> "$COMMIT_MSG_FILE"
    
    # Add suggestions as commented lines
    echo "$SUGGESTIONS" | head -5 | while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "# $line" >> "$COMMIT_MSG_FILE"
        fi
    done
    
    echo "#" >> "$COMMIT_MSG_FILE"
    echo "# Or write your own commit message above" >> "$COMMIT_MSG_FILE"
else
    echo "# Failed to generate AI suggestions" >> "$COMMIT_MSG_FILE"
fi

echo "" >> "$COMMIT_MSG_FILE"
EOF

# Make hook executable
chmod +x "$HOOK_FILE"

echo "✓ Hook installed: $HOOK_FILE"

if [ "$1" = "--global" ]; then
    echo ""
    echo "Global hook template installed. New repositories will automatically"
    echo "include this hook. For existing repos, run:"
    echo "  git init  # in each existing repository"
    echo ""
    echo "Or install locally in existing repos:"
    echo "  ./install-git-hook.sh"
else
    echo ""
    echo "Hook installed for current repository."
    echo "Now when you run 'git commit', AI suggestions will appear in your editor."
fi

echo ""
echo "Make sure to set your Claude API key:"
echo "  export CLAUDE_API_KEY=your_api_key_here"
echo ""
echo "Test it by staging some changes and running:"
echo "  git commit"