# Install committy as a git hook (PowerShell version)
# Usage: .\install-git-hook.ps1 [-Global]

param(
    [switch]$Global
)

$HOOK_TYPE = "prepare-commit-msg"

if ($Global) {
    Write-Host "Installing global git hook template..."
    
    # Create global hooks directory
    $HOOKS_DIR = Join-Path $env:USERPROFILE ".git-templates\hooks"
    New-Item -ItemType Directory -Path $HOOKS_DIR -Force | Out-Null
    
    # Set global template directory
    git config --global init.templateDir (Join-Path $env:USERPROFILE ".git-templates")
} else {
    Write-Host "Installing local git hook..."
    
    # Check if we're in a git repository
    try {
        $gitDir = git rev-parse --git-dir 2>$null
        if ($LASTEXITCODE -ne 0) {
            throw "Not in git repository"
        }
        $HOOKS_DIR = Join-Path $gitDir "hooks"
    }
    catch {
        Write-Error "Error: Not in a git repository. Run from repo root or use -Global flag."
        exit 1
    }
}

$HOOK_FILE = Join-Path $HOOKS_DIR $HOOK_TYPE

# Create the hook script content
$hookContent = @'
#!/bin/bash

# Committy AI-powered commit message hook
# Generated by install-git-hook.ps1

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"
SHA1="$3"

# Only run for regular commits (not merges, rebases, squashes, etc.)
if [ -n "$COMMIT_SOURCE" ]; then
    exit 0
fi

# Check if committy is available
if ! command -v committy >/dev/null 2>&1; then
    echo "# Committy not found in PATH - skipping AI commit message generation" >> "$COMMIT_MSG_FILE"
    exit 0
fi

# Check if we have staged changes
if git diff --cached --quiet; then
    exit 0
fi

# Check for Azure OpenAI configuration
if [ -z "$AZURE_OPENAI_API_KEY" ] || [ -z "$AZURE_OPENAI_ENDPOINT" ] || [ -z "$AZURE_OPENAI_DEPLOYMENT" ]; then
    echo "# Azure OpenAI configuration incomplete - skipping AI commit message generation" >> "$COMMIT_MSG_FILE"
    echo "# Required: AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT" >> "$COMMIT_MSG_FILE"
    exit 0
fi

# Generate AI commit message suggestions
echo "# Generating AI commit message suggestions..." >> "$COMMIT_MSG_FILE"
echo "#" >> "$COMMIT_MSG_FILE"

# Get suggestions and format them as comments
if SUGGESTIONS=$(git diff --cached | committy --stdin --api-key "$AZURE_OPENAI_API_KEY" --endpoint "$AZURE_OPENAI_ENDPOINT" --deployment "$AZURE_OPENAI_DEPLOYMENT" 2>/dev/null); then
    echo "# AI-generated suggestions (uncomment and edit as needed):" >> "$COMMIT_MSG_FILE"
    echo "#" >> "$COMMIT_MSG_FILE"
    
    # Add suggestions as commented lines
    echo "$SUGGESTIONS" | head -5 | while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "# $line" >> "$COMMIT_MSG_FILE"
        fi
    done
    
    echo "#" >> "$COMMIT_MSG_FILE"
    echo "# Or write your own commit message above" >> "$COMMIT_MSG_FILE"
else
    echo "# Failed to generate AI suggestions" >> "$COMMIT_MSG_FILE"
fi

echo "" >> "$COMMIT_MSG_FILE"
'@

# Write the hook file
Set-Content -Path $HOOK_FILE -Value $hookContent -Encoding UTF8

# Make hook executable (this works on Windows with Git Bash)
if (Get-Command "git" -ErrorAction SilentlyContinue) {
    # Use git to set executable bit (works cross-platform)
    git update-index --chmod=+x $HOOK_FILE 2>$null
}

Write-Host "✓ Hook installed: $HOOK_FILE"

if ($Global) {
    Write-Host ""
    Write-Host "Global hook template installed. New repositories will automatically"
    Write-Host "include this hook. For existing repos, run:"
    Write-Host "  git init  # in each existing repository"
    Write-Host ""
    Write-Host "Or install locally in existing repos:"
    Write-Host "  .\install-git-hook.ps1"
} else {
    Write-Host ""
    Write-Host "Hook installed for current repository."
    Write-Host "Now when you run 'git commit', AI suggestions will appear in your editor."
}

Write-Host ""
Write-Host "Make sure to set your Azure OpenAI configuration:"
Write-Host "  `$env:AZURE_OPENAI_API_KEY='your_api_key_here'"
Write-Host "  `$env:AZURE_OPENAI_ENDPOINT='https://your-endpoint.openai.azure.com'"
Write-Host "  `$env:AZURE_OPENAI_DEPLOYMENT='your-deployment-name'"
Write-Host ""
Write-Host "Or for persistent environment variables, use:"
Write-Host "  [Environment]::SetEnvironmentVariable('AZURE_OPENAI_API_KEY', 'your_api_key_here', 'User')"
Write-Host ""
Write-Host "Test it by staging some changes and running:"
Write-Host "  git commit"