using CliWrap;
using CliWrap.Buffered;

namespace Committy.Tests;

public class HookRepairerTests
{
	private const string OLD_HOOK =
		"#!/bin/bash\n# Committy AI-powered commit message hook\n# Generated by install-git-hook.sh\ngit diff --cached | committy --no-git\n";

	private const string FOREIGN_HOOK =
		"#!/bin/sh\n# my own hook\necho \"running my hook\"\n";

	[Theory]
	[InlineData(OLD_HOOK, true)]
	[InlineData(FOREIGN_HOOK, false)]
	public void IsCommittyManaged_DetectsCommittyHooks(string content, bool expected)
	{
		Assert.Equal(expected, HookInstaller.IsCommittyManaged(content));
	}

	private static async Task<string> NewRepoAsync()
	{
		string dir = Path.Combine(Path.GetTempPath(), "committy-repair-" + Path.GetRandomFileName());
		Directory.CreateDirectory(dir);

		// Init with an empty template so a globally-configured hook template doesn't
		// pre-populate prepare-commit-msg; each test controls the hook state itself.
		string emptyTemplate = Path.Combine(dir, ".empty-template");
		Directory.CreateDirectory(emptyTemplate);
		await Cli.Wrap("git")
			.WithArguments(["-C", dir, "init", $"--template={emptyTemplate}"])
			.ExecuteBufferedAsync();

		return dir;
	}

	private static string WriteHook(string repo, string content)
	{
		string hookPath = Path.Combine(
			repo,
			".git",
			"hooks",
			"prepare-commit-msg");
		Directory.CreateDirectory(Path.GetDirectoryName(hookPath)!);
		File.WriteAllText(hookPath, content);

		return hookPath;
	}

	[Fact]
	public void IsCommittyManaged_DetectsCurrentTrampoline()
	{
		Assert.True(HookInstaller.IsCommittyManaged(HookInstaller.Trampoline));
		Assert.True(HookInstaller.IsCurrentTrampoline(HookInstaller.Trampoline));
	}

	[Fact]
	public async Task RepairRepoAsync_AlreadyTrampoline_ReportsAlreadyCurrent()
	{
		string repo = await NewRepoAsync();
		try
		{
			WriteHook(repo, HookInstaller.Trampoline);

			HookRepairResult result = await HookRepairer.RepairRepoAsync(repo, false, false);

			Assert.Equal(HookRepairOutcome.AlreadyCurrent, result.Outcome);
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}

	[Fact]
	public async Task RepairRepoAsync_Backup_PreservesPreviousHook()
	{
		string repo = await NewRepoAsync();
		try
		{
			string hookPath = WriteHook(repo, OLD_HOOK);

			await HookRepairer.RepairRepoAsync(repo, false, true);

			Assert.Equal(OLD_HOOK, await File.ReadAllTextAsync(hookPath + ".bak"));
			Assert.Equal(HookInstaller.Trampoline.Trim(), (await File.ReadAllTextAsync(hookPath)).Trim());
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}

	[Fact]
	public async Task RepairRepoAsync_DryRun_DoesNotModifyStaleHook()
	{
		string repo = await NewRepoAsync();
		try
		{
			string hookPath = WriteHook(repo, OLD_HOOK);

			HookRepairResult result = await HookRepairer.RepairRepoAsync(repo, true, false);

			Assert.Equal(HookRepairOutcome.Updated, result.Outcome);
			Assert.Equal(OLD_HOOK, await File.ReadAllTextAsync(hookPath));
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}

	[Fact]
	public async Task RepairRepoAsync_ForeignHook_IsLeftUntouched()
	{
		string repo = await NewRepoAsync();
		try
		{
			string hookPath = WriteHook(repo, FOREIGN_HOOK);

			HookRepairResult result = await HookRepairer.RepairRepoAsync(repo, false, false);

			Assert.Equal(HookRepairOutcome.SkippedForeign, result.Outcome);
			Assert.Equal(FOREIGN_HOOK, await File.ReadAllTextAsync(hookPath));
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}

	[Fact]
	public async Task RepairRepoAsync_NoHook_ReportsNoHook()
	{
		string repo = await NewRepoAsync();
		try
		{
			HookRepairResult result = await HookRepairer.RepairRepoAsync(repo, false, false);

			Assert.Equal(HookRepairOutcome.NoHook, result.Outcome);
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}

	[Fact]
	public async Task RepairRepoAsync_StaleCommittyHook_IsReplacedWithTrampoline()
	{
		string repo = await NewRepoAsync();
		try
		{
			string hookPath = WriteHook(repo, OLD_HOOK);

			HookRepairResult result = await HookRepairer.RepairRepoAsync(repo, false, false);

			Assert.Equal(HookRepairOutcome.Updated, result.Outcome);
			Assert.Equal(HookInstaller.Trampoline.Trim(), (await File.ReadAllTextAsync(hookPath)).Trim());
		}
		finally
		{
			Directory.Delete(repo, true);
		}
	}
}
